-- --------------------------------------------------------
-- Arrebol Consuntancy
-- version 1.0.1
-- http://www.arrebolconsultancy.com
-- --------------------------------------------------------

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
-- SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

USE `apo_pro_com_april_ten`;

-- --------------------------------------------------------------------
-- 
-- Estructura para la vista `APC_CASH_REGISTER_CURDATE_BY_USER_VIEW`
--
-- Sirve para obtener todos los pagos que recabo un asesor en el día.
-- 
DROP TABLE IF EXISTS APC_LOAN_BY_RENOVATION;
DROP TABLE IF EXISTS APC_USER_MOBILE_PREFERECE;
DROP TABLE IF EXISTS APC_USER_BY_OFFICE_HAS_PERMISSION;
DROP TABLE IF EXISTS APC_PERMISSION;
DROP TABLE IF EXISTS APC_USER_BY_OFFICE;
DROP TABLE IF EXISTS APC_LOAN_BY_USER;
DROP TABLE IF EXISTS APC_LOAN_FEE_NOTIFICATION;
DROP TABLE IF EXISTS APC_LOAN_DETAIL;
DROP TABLE IF EXISTS APC_USER;
DROP TABLE IF EXISTS APC_HUMAN_RESOURCE_BY_OFFICE;
DROP TABLE IF EXISTS APC_LOAN;
DROP TABLE IF EXISTS APC_LOAN_TYPE;
DROP TABLE IF EXISTS APC_PEOPLE;
DROP TABLE IF EXISTS APC_HUMAN_RESOURCE_HAS_ROUTE;
DROP TABLE IF EXISTS APC_HUMAN_RESOURCE;
DROP TABLE IF EXISTS APC_ROUTE;
DROP TABLE IF EXISTS APC_ROLE;
DROP TABLE IF EXISTS APC_OFFICE;
DROP TABLE IF EXISTS APC_ERROR_APP_LOG;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;